services:
  medods-task:
    build: .
    container_name: medods-task
    ports:
      - "8080:8080"
    environment:
      - HTTP_HOST=localhost
      - HTTP_PORT=8080
      - JWT_SECRET=very_secret_key
      - ACCESS_EXPIRATION_SECONDS=3600
      - REFRESH_EXPIRATION_SECONDS=604800
      - LOG_LEVEL=debug
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_MAX_OPEN_CONNS=10
      - DB_MAX_IDLE_CONNS=5
      - GIN_MODE=release
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal: